apiVersion: apps/v1
kind: Deployment
metadata:
  name: akscicd
  labels:
    app: akscicd
    kubernetes.azure.com/generator: devhub
  namespace: namespace-workflow-1724751279027
spec:
  replicas: 1
  selector:
    matchLabels:
      app: akscicd
  template:
    metadata:
      labels:
        app: akscicd
    spec:
      containers:
        - name: akscicd
          image: billapps.azurecr.io/image-workflow-1724751279027:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
