apiVersion: v1
kind: Service
metadata:
  name: akscicd
  namespace: namespace-workflow-1724751279027
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: akscicd
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080